### ISSUE TITLE
Oculus Killer executable marked as malicious

### ISSUE THREAD

**Issue by Jazun** [sulliops/OculusKiller#1] opened 2022-06-08 14:31 UTC
Gets marked by 32 Vendors as malicious.. I'll pass. I'm good using task manager.

https://www.virustotal.com/gui/file/906eed88d8924ab931f8bad6c2ad8b92fa42947821c7a9f9347123df4b02718e

**Comment by sulliops** [comment] 2022-06-08 14:36
**For v2.0.0:**

The issue is with the [ps2exe module](https://github.com/MScholtes/PS2EXE) that I use to create a .exe executable from the .ps1 PowerShell script. The README includes the exact build instructions that I used for the release, as well as how to build it yourself. The ps2exe module has been abused by scammers and thus most every executable made with it is now being picked up by antivirus vendors. 

Since this project isn't shaking the world at the moment, I haven't bothered to do anything about this. If you're concerned about this false positive being anything but, simply use the raw .ps1 PowerShell script.

--------

**For v3.0.0 and newer:**

Both the executable and installer files may be marked as malicious by browsers or by Windows, however these are false positives. See the VirusTotal results for the v3.1.1 executable, which shows one false positive: https://www.virustotal.com/gui/file/bad0c69547c2b4b3f8e9a6c0daa3cbbc47bd578805749d99e38faddbc0de3cd6?nocache=1

The false positives are caused by a lack of code-signing, which is too expensive for a simple application like this. More details can be found alongside each release, as I go over the issue each time I create a release. If you're concerned about what the program does, you can analyze the source code and build it manually with Visual Studio 2022.

**Closed as completed by sulliops** 2022-06-08 14:36 UTC
Labels: wontfix
